#+STARTUP: content
#+AUTHOR: Robert Clay
#+HUGO_BASE_DIR: .
#+HUGO_AUTO_SET_LASTMOD: t
* Pages
  :PROPERTIES:
  :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :noauthor true :nocomment true :nodate true :nopaging true :noread true
  :EXPORT_HUGO_MENU: :menu main
  :EXPORT_HUGO_SECTION: pages
  :EXPORT_HUGO_WEIGHT: auto
  :END:
** Main page
   :PROPERTIES:
   :EXPORT_FILE_NAME: page-title
   :END:
This will be on of the pages separate from the blog posts. It will be longer
* Posts
  :PROPERTIES:
  :EXPORT_HUGO_SECTION: blog
  :END:
** Topic                                                             :@topic:
*** TODO Post Title                                               :post:tags:
    :PROPERTIES:
    :EXPORT_DATE: 2017-12-19
    :EXPORT_FILE_NAME: post-title-in-slug-form
    :END:

    - State "TODO"       from "DONE"       [2020-12-15 Tue 22:31]
    Content

    More Content

    #+BEGIN_SRC bash -l 7 :hl_lines 8
      echo 'Some source code content'
      echo 'This line will be highlighted'
      echo "This one won't"
    #+END_SRC

**** Post Sub-Heading
     This is another section within the post.

*** TODO Draft Post Title
    :PROPERTIES:
    :EXPORT_FILE_NAME: draft-post-title
    :END:

    This article *will* be exported but will be marked ~draft = true~ in the front matter.

*** DONE First post
    :PROPERTIES:
    :EXPORT_FILE_NAME: bobby-test-post
    :EXPORT_DATE: 2020-12-13
    :END:
   [2020-12-15 Tue], #first_post
   
   This is the first of many posts to come. I had never considered my self a
   blogger type, but I have been learning some things recently and I feel like a
   blog is a great way to share what I have been learning is a ...oddly
   old fashioned manner. This past year I went from using Google docs to keep
   notes at work, so today finding myself unwilling to use anything less than
   Emacs and Org mode for a surprising amount of my day to day note taking and
   organization. It was a lot to learn, but the journey was worth it, and I hope
   to share not just what I have been learning about this past year (2020 was
   one for the record books in more ways than one), but I haven't really felt
   like I had a place to tell my story until now.

   These days all the young kids in Japan want to grow up and be a YouTuber.
   YouTube is a fascinating medium, and the amount of things you can learn and
   see there is staggering. But I have found myself gravitating to text these
   days and hope that a simple presentation can provide some counterpoint to the
   rest of the world that seems to be happily consuming ever increasing amounts
   of loud, noise, colorful, and occasionally obnoxious video content in various
   forms.

   ...wow, I started off this blog with a little "get off my lawn" soap-box
   speech. This is going to be interesting. 
* Footnotes
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (auto-fill-mode 1)
# eval: (org-hugo-auto-export-mode)
# End:
